# Generated by Django 5.0.4 on 2024-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_mess_sender_alter_chat_mess_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_mess',
            name='sender',
        ),
    ]
